name: 'Update Pull Requests to Draft on Labels'
description: 'Updates a pull request to a Draft on provided labels'
author: 'Devin Buhl'
inputs:
  token:
    description: >-
      GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)
    default: ${{ github.token }}
    required: false
  labels:
    description: >-
      A comma or newline separated list of labels.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
